services:
  #watchtower:
  #  image: containrrr/watchtower:latest
  #  command:
  #    - "--label-enable"
  #    - "--interval"
  #    - "30"
  #    - "--rolling-restart"
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock

  reverse-proxy:
    image: traefik:v3.2
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=contact@yuki6942.de"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock

  web:
    build:
      context: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`yuki6942.de`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
      - "traefik.http.services.web.loadbalancer.server.port=3000"
      #- "com.centurylinklabs.watchtower.enable=true"
    env_file:
      - .env.local

volumes:
  letsencrypt:
